### ISSUE TITLE
Issues importing modules

### ISSUE THREAD

**Issue by abachma2** [arfc/openmcyclus#3]
I'm working on writing some functions, and trying to write tests as I go. However, the module with the functions I am trying to test isn't being found. 

What I'm doing:
- going to `openmcyclus` directory
- activating correct conda environment
- running `pip install .`
- running `pytest`

Things I have tried:
- running pytest from `tests/unit_tests` directory
- adding empty `__init__.py` files to every directory in the project
- Adding empty `__init__.py`to only the `openmcyclus/openmcyclus` directory. 
- Adding `~/openmcyclus` to my PYTHONPATH environment variable. 
None of these seem to work, I get `ModuleNotFoundError: No module named 'depletion'` every single time. Any help/advice is welcome. This is all being done on the `depletion` branch of my repo: https://github.com/abachma2/openmcyclus/tree/depletion

**Comment by samgdotson** [comment]
Your import statement in ``test_depletion.py`` is (I think this is the one causing problems)

```py
import depletion
```

Which assumes the following hierarchy

```
openmcyclus/
tests/
-- test_depletion.py
-- depletion.py
```

You actually have

```
openmcyclus/
-- depletion.py
-- DepleteReactor.py
tests/
-- test_depletion.py
```

So you need two things: 
1. An ``__init__.py`` file in the ``openmcyclus/`` directory.
2. To change your import statement to ``import openmcyclus.depletion as depletion``

**Comment by abachma2** [comment]
Thanks for the quick feedback @samgdotson. I was already trying your first point, I was missing the second point. And since these functions aren't in a class (maybe they will be later) the command is `from openmcyclus import depletion`. Your command is for importing a class, while I am trying to just import a module of functions. 

But none the less, I forgot about that part of the import statement, and you helped me fix the issue. Thank you!
